# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import judge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=100)),
                ('rank', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=128, unique=True)),
                ('link', models.URLField()),
                ('statement', models.TextField()),
                ('num_submissions', models.IntegerField(default=0)),
                ('num_accepted', models.IntegerField(default=0)),
                ('num_wa', models.IntegerField(default=0)),
                ('num_re', models.IntegerField(default=0)),
                ('num_tle', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('time_limit', models.IntegerField(default=1000)),
                ('source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NT', 'Not tested'), ('CE', 'Compile Error'), ('TS', 'Tested')], default='NT', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Coder')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to=judge.models.in_upload_path)),
                ('output_file', models.FileField(upload_to=judge.models.out_upload_path)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='coder',
            name='problems_tried',
            field=models.ManyToManyField(related_name='problems_tried', to='judge.Problem'),
        ),
        migrations.AddField(
            model_name='coder',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
