# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_submission_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='lang',
            field=models.CharField(choices=[('C', 'GNU C'), ('CPP', 'GNU C++'), ('JAVA', 'Java 1.7'), ('PYTH', 'Python 2.7'), ('PYTH3', 'Python 3')], default='C', max_length=4),
        ),
    ]
