# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_auto_20160226_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='num_tests',
            field=models.IntegerField(default=0),
        ),
    ]
