# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_auto_20160321_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnevaluatedSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('C', 'GNU C'), ('CPP', 'GNU C++'), ('JAVA', 'Java 1.7'), ('PYTH', 'Python 2.7'), ('PYTH3', 'Python 3')], default='C', max_length=4)),
                ('code', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Coder')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='unevaluated',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.UnevaluatedSubmission'),
        ),
    ]
