# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_auto_20160405_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.Coder'),
        ),
    ]
