# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_auto_20160405_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unevaluatedsubmission',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='unevaluatedsubmission',
            name='submitter',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='unevaluated',
        ),
        migrations.AddField(
            model_name='coder',
            name='problems_ac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems_ac', to='judge.Problem'),
        ),
        migrations.RemoveField(
            model_name='coder',
            name='problems_tried',
        ),
        migrations.AddField(
            model_name='coder',
            name='problems_tried',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems_tried', to='judge.Problem'),
        ),
        migrations.DeleteModel(
            name='UnevaluatedSubmission',
        ),
    ]
