# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0009_auto_20160522_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
