# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0010_submission_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='num_ce',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('NT', 'Not tested'), ('CE', 'Compile Error'), ('TL', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('AC', 'Accepted')], default='NT', max_length=2),
        ),
    ]
