# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0011_auto_20160522_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='num_accepted',
            new_name='num_ac',
        ),
    ]
